# Generated by Django 5.2 on 2025-05-07 17:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_service', '0002_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('image_url', models.URLField(help_text='URL to the stored scan image', max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='auth_service.patient')),
            ],
            options={
                'ordering': ['-scan_date'],
                'indexes': [models.Index(fields=['patient'], name='imaging_ser_patient_c4a220_idx'), models.Index(fields=['scan_date'], name='imaging_ser_scan_da_858f18_idx')],
            },
        ),
    ]
