# Generated by Django 5.2 on 2025-05-07 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imaging_service', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scan',
        ),
    ]
