# Generated by Django 5.2 on 2025-05-07 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0002_patient'),
        ('imaging_service', '0002_delete_scan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
